server:
  port: 9001
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos.q7w.cn:8848
      namespace: 60b4bf51-c630-4468-9d42-2a8671c08e9c
    gateway:
      discovery:
        locator:
          enabled: true


feign:
  hystrix:
    enabled: true
