server:
  port: 9001
spring:
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      namespace: 60b4bf51-c630-4468-9d42-2a8671c08e9c
feign:
  hystrix:
    enabled: true
