server:
  port: 9021

spring:
  application:
    name: UserCoreService
  boot:
    admin:
      client:
        url: http://localhost:8769
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      namespace: 60b4bf51-c630-4468-9d42-2a8671c08e9c

management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有节点
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS  #显示详细信息

